hslavich_onelogin_saml:
    # Basic settings
    idp:
        entityId: 'urn:example:idp'
        singleSignOnService:
            url: 'http://localhost:7000/signin'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        singleLogoutService:
            url: 'https://localhost:7000/signout'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        x509cert: 'MIIDqTCCApGgAwIBAgIUW+a7SDZCPu/DQigF2GgeaKYNES0wDQYJKoZIhvcNAQELBQAwZDELMAkGA1UEBhMCVVMxETAPBgNVBAgMCE5ldyBZb3JrMRAwDgYDVQQHDAdCdWZmYWxvMQswCQYDVQQKDAJVQjEjMCEGA1UEAwwaQ0NSIFRlc3QgSWRlbnRpdHkgUHJvdmlkZXIwHhcNMjMxMDE2MjAxOTQ5WhcNNDMxMDExMjAxOTQ5WjBkMQswCQYDVQQGEwJVUzERMA8GA1UECAwITmV3IFlvcmsxEDAOBgNVBAcMB0J1ZmZhbG8xCzAJBgNVBAoMAlVCMSMwIQYDVQQDDBpDQ1IgVGVzdCBJZGVudGl0eSBQcm92aWRlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMhNzjlavla5eLhZxYQATrS0kPNcTVrM7gTlAIAesr9rrtItWxc9i6GuRTHWJ46OD1k4X8bMNCpa51okag5oxIRESRRiKxpP8oJYlrFwsR+NtJ02ais/POnlwr0EcNjOwOYcn9yZeQdWWCpwpb030R5/uEUSfNvCAXMXEeLB0vcHXaKXm+RPxIfCUJAO1Id3bBukOqsDohvNXFGrhGIK9njbcj5nVMQbX4b3Cvb4EnebtpiZnJPa9DtY8ee5YwSvY/rhpSB5bKWGarXwJ2MWEZw9xlxrotcTJ/8RtfQ2f93zcf9P2fp5ZKE9EIWQoAV2bDINPV/rUdv+65pzmaTUcVcCAwEAAaNTMFEwHQYDVR0OBBYEFLpqFGmCBq9nf0Au2PmWBdHQ0IjVMB8GA1UdIwQYMBaAFLpqFGmCBq9nf0Au2PmWBdHQ0IjVMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAA7m2TcZO8tgFByXFgvEBFFTvsfkG29aNVgvPAoMrZB/O3uGleZUVgcIoJgJ8uirceAtlh0XaU/O6vV3FmtgVVYDEFYgd1OG42xDyKne8Yk/ZvZL1zli/LOngTcR2nN1b6SwBMhrsQE90wPcgCkt0uuTjRHPVf84B5jKuZTFfzxaIFFgIJ7q4U3k8/hc+IT5B44i9dHzFwj6lfDbktxugEONDSjS8CJFAAGAxsI/J7e6aEo5bi3YrNZVIHCxsArUjXNJzNzTxvbbyG+EW/WuuJPg1xJCxQ+nDBiOgoSKh9eFjSO+FlT8Uqi6yn5dEmYTp/jjllWyMJQudUZ40Wk1lWA='
    sp:
        entityId: 'xdmod-sp'
        assertionConsumerService:
            url: 'https://localhost/saml/acs'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        singleLogoutService:
            url: 'https://localhost/saml/logout'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        privateKey: ''
    # Optional settings
    strict: true
    debug: true
    security:
        nameIdEncrypted: false
        authnRequestsSigned: false
        logoutRequestSigned: false
        logoutResponseSigned: false
        wantMessagesSigned: false
        wantAssertionsSigned: false
        wantNameIdEncrypted: false
        requestedAuthnContext: true
        signMetadata: false
        wantXMLValidation: true
        relaxDestinationValidation: false
        destinationStrictlyMatches: true
        rejectUnsolicitedResponsesWithInResponseTo: false
        signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
        digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
    contactPerson:
        technical:
            givenName: 'Tech User'
            emailAddress: 'techuser@example.com'
        support:
            givenName: 'Support User'
            emailAddress: 'supportuser@example.com'
        administrative:
            givenName: 'Administrative User'
            emailAddress: 'administrativeuser@example.com'
    organization:
        en:
            name: 'Example'
            displayname: 'Example'
            url: 'http://example.com'
