nbgrp_onelogin_saml:
    onelogin_settings:
        default:
            # Basic settings
            idp:
                entityId: 'https://xdmod/realms/xdmod'
                singleSignOnService:
                    url: 'https://xdmod:7000/'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                singleLogoutService:
                    url: 'https://xdmod:7000/signout'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                x509cert: ''
            sp:
                entityId: 'xdmod-sp'
                assertionConsumerService:
                    url: 'https://xdmod/saml/acs'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                singleLogoutService:
                    url: 'https://xdmod/saml/logout'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                privateKey: ''
            # Optional settings
            strict: false
            debug: true
            security:
                nameIdEncrypted: false
                authnRequestsSigned: false
                logoutRequestSigned: false
                logoutResponseSigned: false
                wantMessagesSigned: false
                wantAssertionsSigned: false
                wantNameIdEncrypted: false
                requestedAuthnContext: true
                allowRepeatAttributeName: true
                signMetadata: false
                wantXMLValidation: true
                relaxDestinationValidation: false
                destinationStrictlyMatches: true
                rejectUnsolicitedResponsesWithInResponseTo: false
                signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
                digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
            contactPerson:
                technical:
                    givenName: 'Tech User'
                    emailAddress: 'techuser@example.com'
                support:
                    givenName: 'Support User'
                    emailAddress: 'supportuser@example.com'
                administrative:
                    givenName: 'Administrative User'
                    emailAddress: 'administrativeuser@example.com'
            organization:
                en:
                    name: 'Example'
                    displayname: 'Example'
                    url: 'http://example.com'
