# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
jobs:
  build:
    parameters:
      install-type:
        type: string
    docker:
      # Specify the version you desire here
      - image: tools-ext-01.ccr.xdmod.org/xdmod-9.0.0:centos7.8-0.1
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      XDMOD_REALMS: 'jobs,storage,cloud'
      XDMOD_IS_CORE: yes
      XDMOD_INSTALL_DIR: /xdmod
      XDMOD_TEST_MODE: << parameters.install-type >>
    steps:
      - checkout
      # We need to update our acct before we can enable docker layer caching.
      #- setup_remote_docker:
      #    docker_layer_caching: true
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: composer install --no-progress
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: mkdir -p ~/phpunit
      - run: mkdir /tmp/screenshots
      - run:
          name: Setup Environment Variables
          command: |
            echo "export XDMOD_SOURCE_DIR=${CIRCLE_WORKING_DIRECTORY}" >> $BASH_ENV
            echo "export SHIPPABLE_BUILD_DIR=${CIRCLE_WORKING_DIRECTORY}" >> $BASH_ENV
      - run: ~/bin/buildrpm xdmod
      - run: ./tests/ci/bootstrap.sh
      - run: ./tests/ci/validate.sh
      - run: composer install --no-progress
      - run: git remote add upstream https://github.com/ubccr/xdmod.git
      - run: ./tests/ci/scripts/qa-test-setup.sh
      - run: composer install --no-progress
      - run: ./tests/regression/runtests.sh
      - run: mv ./configuration/organization.json ./configuration/organization.json.old
      - run: mv ./configuration/portal_settings.ini ./configuration/portal_settings.ini.old
      - run: cp /etc/xdmod/portal_settings.ini ./configuration/portal_settings.ini
      - run: cp /etc/xdmod/organization.json ./configuration/organization.json
      - run: ./tests/integration/runtests.sh --junit-output-dir ~/phpunit
      - run: ./tests/regression/post_ingest_test.sh --junit-output-dir ~/phpunit
      - run: ./tests/component/runtests.sh --junit-output-dir ~/phpunit
      - run: ./tests/ui/runtests.sh --headless --log-junit ~/phpunit
      - run:
          name: 'Run SSO Tests'
          command: |
            ./tests/ci/samlSetup.sh
            ./tests/ui/runtests.sh --headless --log-junit ~/phpunit --sso
            ./vendor/phpunit/phpunit/phpunit -c ./tests/integration/phpunit.xml.dist --testsuite sso --log-junit ~/phpunit/xdmod-sso-integration.xml
      - run: mv ./configuration/portal_settings.ini.old ./configuration/portal_settings.ini
      - run: test `fgrep -v ' [ssl:warn] ' /var/log/xdmod/apache-error.log | wc -l` = 0
      - store_artifacts:
          path: /tmp/screenshots
      - store_artifacts:
          path: /var/log/xdmod

workflows:
  full-build:
    jobs:
      - build:
          matrix:
            parameters:
              install-type: ["fresh_install", "upgrade"]
